use_frameworks!
platform :ios, '9.3'

target 'FlatDropdown_Example' do
    pod 'FlatDropdown', :path => '../'
    pod 'FlatField', '~> 0.0.5'
    
    target 'FlatDropdown_Tests' do
        inherit! :search_paths
        
    end
end

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
